### route using GET
GET http://localhost:3001 HTTP/1.1

### route using POST
//important! leave empty line between header and body!! 
POST http://localhost:3001/new HTTP/1.1
Content-Type: application/json

{
    "description": "Test from Client Rest"
}

### Delete route using delete
DELETE http://localhost:3001/delete/3 HTTP/1.1